### ISSUE TITLE
GPSPRINGSECURITYCORE-240: AuthAjax does not return JSON

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#194]
Original Reporter: nuukular
Environment: Grails 2.2.3
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-240

As with previous versions the spring security core plug-in does not handle ajax calls correctly. Instead of the expected JSON, a full html page is returned.
To reproduce these steps:
- Log-in
- Delete cookie
- Issue an ajax call
- A full html page is returned instead of the expected JSON. Fortunately there are no more redirects as with previous versions, therefore this can be now handled correctly via the http status code.

As already reported previously, this has been a workaround for earlier versions. I am including it, as this issue might be similar to earlier version:

    @Override
    public void onAuthenticationSuccess(final HttpServletRequest request, final HttpServletResponse response,
                                        final Authentication authentication) throws ServletException, IOException {
       if (SpringSecurityUtils.isAjax(request)) {
          _requestCache.removeRequest(request, response);
       }
       super.onAuthenticationSuccess(request, response, authentication);
       // always remove the saved request
       _requestCache.removeRequest(request, response);
    }

**Comment by nialloconnor** [comment]
@burtbeckwith I'm running into an issue that I believe is related to this and it's unclear about the expected way to handle Ajax authentication redirects. I have a JS application that calls out to another service (Grails 2.4.4, Spring Sec Core 2.0.0, Spring, Sec CAS 2.0.0) to retrieve its account settings when it loads in the browser. The request hits the account settings application then redirects to CAS to verify the session, then back to the apps auth handler (j_spring_security) and on to the / root context (defaultTargetUrl) of the app, this last hop should have landed at the DefaultSavedRequest and not the defaultTargetUrl as successHandler.alwaysUseDefault = false. 
I see in the debug logs: 
`savedrequest.HttpSessionRequestCache  - Removing DefaultSavedRequest from session if present`
Which I believe is coming from the line added as part of this issue. What is the expected behaviour here? Is it nesscary to define a ajaxSuccess handler? Why is the treatment different for ajax requests not allowing them to simply follow redirects?
