### ISSUE TITLE
GPSPRINGSECURITYCORE-201: Caching of config in SpringSecurityUtils results in using old config values

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#200]
Original Reporter: ronnylovtangen
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-201

We created a plugin with our custom authenticationProvider and userDetailsService.
As per the documentation at http://grails-plugins.github.com/grails-spring-security-core/docs/manual/guide/10%20Authentication%20Providers.html we registered the provider with a config property:

```groovy
application.config.grails.plugins.springsecurity.providerNames = [
   'usrPwdAuthenticationProvider',
   'anonymousAuthenticationProvider',
   'rememberMeAuthenticationProvider']
```

This was done in our plugins PluginNameGrailsPlugin doWithSpring, and it worked as expected.

However, after adding plugin spring-security-ui 0.2, our custom authentication provider was no longer used.

This was due to the fact that `SpringSecurityUtils.getSecurityConfig()` were called by spring-security-ui before the config property  `grails.plugins.springsecurity.providerNames` was set by our plugin. And because of the caching in SpringSecurityUtils property `_securityConfig`, spring-security-core was not able to see the new values set by our plugin, but used the stale values from when spring-security-ui was loaded.

As a workaround, we added the config values directly to SpringSecurityUtils as well:
```groovy
SpringSecurityUtils.securityConfig.providerNames = application.config.grails.plugins.springsecurity.providerName
```

If config values from DefaultSecurityConfig and other custom config files from spring-security-xxx plugins were loaded into the global config object (grailsApplication.config) rather than being cached in SpringSecurityUtils, there would be no risk on using stale values.
But there might be other reasons to store values in SpringSecurityUtils?

**Comment by alvarosanchez** [comment]
Reported by @rlovtangen

**Comment by alvarosanchez** [comment]
I think this can be fixed just by controlling when your plugin is loaded. In this case:

```
def loadAfter = ['springSecurityCore']
def loadBefore = ['springSecurityUi']
```

All spring-security-* subplugins are using `SpringSecurityUtils.securityConfig` at the very beginning, so I'm a bit reluctant to change the behaviour now.

@rlovtangen would you be able to apply my suggestion above, or the issue is too old and not reproducible?

**Comment by rlovtangen** [comment]
Sorry, the issue is quite old and I'm not using spring-security-ui anymore. Tried to add spring-security-ui and remove the line where I set SpringSecurityUtils.securityConfig.providerNames myself, but wasn't able to reproduce the issue.
I also tried to add 
````
def loadBefore = ['springSecurityUi']
````
to my plugin, but spring-security-ui is loaded first anyhow, even before spring-security-core:
````
Configuring Spring Security UI ...
... finished configuring Spring Security UI

Configuring Spring Security Core ...
... finished configuring Spring Security Core

Configuring Spring Security UsrPwd ...
````
