### ISSUE TITLE
GPSPRINGSECURITYCORE-245: OPTIONS http request to protected RestfulController action always resulted with 301 and action method never called.   

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#242]
Original Reporter: xmlking
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-245

**Comment by orubel** [comment]
Ok so I tried to ask questions in the forum to avoid posting this but I see a similar issue. I have the CORS interceptor in my plugin and the project that I am using it with can do everything (GET, PUT,POST,DELETE) for all endpoints.

I am also using it with spring-security-core:3.0.3 so I can login, checks roles per endpoint and return resource.

HOWEVER... when I try the request.method of OPTIONS, it NEVER hits my Interceptor.

Here is are my dependencies in the plugin:
    compile 'org.grails.plugins:cache:3.0.2'
    compile 'org.springframework.boot:spring-boot-starter-logging'
    compile 'org.springframework.boot:spring-boot-autoconfigure'
    provided 'org.springframework.boot:spring-boot-starter-tomcat'
    compile 'org.grails.plugins:spring-security-core:3.0.3'
    compile 'org.grails:grails-web'
    compile 'org.grails:grails-dependencies'

and the application:
    compile("org.grails.plugins:api-framework:0.1-SNAPSHOT")
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-dependencies"
    compile 'org.grails.plugins:mongodb:5.0.2'
    compile "org.mongodb:mongodb-driver:3.0.2"
    runtime 'org.springframework.data:spring-data-mongodb:1.8.1.RELEASE'
    provided 'org.springframework.boot:spring-boot-starter-tomcat'
    compile 'org.grails.plugins:spring-security-core:3.0.3'
    compile "org.grails.plugins:hibernate"
    compile "org.hibernate:hibernate-ehcache"
    testCompile "org.grails.plugins:geb"
    testCompile "org.grails:grails-plugin-testing"

Since I'm handling all the endpoints manually and the request methods, OPTIONS must be being obstructed and not being routed. But it is giving me a '200 OK':

* Connected to localhost (127.0.0.1) port 8080 (#0)
> OPTIONS /v0.1/post/show/1 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
> Cookie: JSESSIONID=7F7B10DCD31A5850FE1C7E529C3B46A0; apiTest=YWRtaW46MTQ1ODU5MTYzOTEyMDowMWI3YWZhOGI4NTdiZTkwMDVlNGMyZWU1OTc1YmYwMA
> 
< HTTP/1.1 200 OK
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
< Content-Length: 0
< Date: Mon, 07 Mar 2016 20:20:53 GMT

Hate to reopen this or file a new ticket but is it possible to have someone take a look at why this would be holding on to the OPTIONS and not routing? Does it have a plugin dependency?
