### ISSUE TITLE
GPSPRINGSECURITYCORE-65: Add flash messages after successful login and logout

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#297]
Original Reporter: alexandergeorge
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-65

Add flash messages for login.auth and logout.index similar to those provided for login.authfail.
.

**Comment by ddelponte** [comment]
It is not clear to me what the original intent of this issue was.

The functionality provided by the `Login` and `Logout` controllers may be easily overridden to provide a `flash` message that may be presented to the user.

Not constructing a flash message by default upon successful login or logout seems a sensible default to me.

If others disagree, please provide feedback, else I will close this ticket in the not-to-distant future :)

**Comment by ddelponte** [comment]
No feedback received.  Closing.
