### ISSUE TITLE
GPSPRINGSECURITYCORE-114: when i use Multiple Data Sources Support,but i can not login using plugin spring-security-core 1.2.1.

### ISSUE THREAD

**Issue by graemerocher** [grails-plugins/grails-spring-security-core#338]
Original Reporter: shipf_grails
Environment: when i use Multiple Data Sources Support,but i can not login using plugin spring-security-core 1.2.1.
Version: Grails-Spring-Security-Core 1.2
Migrated From: http://jira.grails.org/browse/GPSPRINGSECURITYCORE-114

ubuntu 11.04
grails 2.0.0.m2
spring-security-core 1.2.1

when i use Multiple Data Sources Support,but i can not login using plugin spring-security-core 1.2.1.

if the data is created by multiple data sources ,also i can not login in single data source code.

**Comment by ddelponte** [comment]
The approach to password encoding has been changed in more recent versions of grails-spring-security-core.

Password encoding is no longer done in the `User` domain class with `beforeInsert()`.  

Instead, `UserPasswordEncoderListener` is used.

More information is available at https://grails-plugins.github.io/grails-spring-security-core/3.2.x/index.html#usingControllerAnnotations

This bug is fixed if your app is using Spring Core version 3.1.2 or later and GORM 6.0.10 or later.

I will mark this as fixed and close it.
