### ISSUE TITLE
3.0.0.M1 -> Grails 3.0.7 and 3.0.8 -> Can not apply staticRules to REST resource URLs

### ISSUE THREAD

**Issue by codeconsole** [grails-plugins/grails-spring-security-core#385]
For a simple working example, view
https://github.com/codeconsole/grails3bugs

Run the app and try to view
http://localhost:8080/cars.json

which has the following staticRules:

		'/car/**':          ['permitAll'],
		'/cars.*':          ['permitAll']	

You will be redirected to 
/login/auth

**Comment by graemerocher** [comment]
See explanation of the cause of this problem here https://github.com/grails/grails-core/issues/9343#issuecomment-147637671

The issue is that the configuration:

     '/cars.*':          ['permitAll']

Becomes a nested map such as `[cars:['*':['permitAll']]]`. I don't believe we will be fixing this in core, the plugin will need to compensate. 

Really as I said the plugin needs to be updated to use the new configuration APIs in Grails 3, as it is still using manual merging and Grails 2.x techniques via `ConfigObject` etc.

**Comment by hakanernam** [comment]
@graemerocher  Could you open "the new configuration APIs in Grails 3"? Reading through security plugin, I can see what you mean by manual merging. There seems to be a good potential for simplification. I also read grails documentation on plugins but could not really see what the new API is.

I would like to attempt to help in such a simplification using the right methods, since I believe many people need this plugin to be in good shape. As things stand, the plugin at Milestone1 breaks a 3.1.0.M2 grails application. I want to upgrade to 3.1.0.M2 due to problems with 3.0.9, but cannot because of this.

**Comment by graemerocher** [comment]
Defaults should go into `grails-app/conf/plugin.yml`

See 
https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/grails/config/Config.groovy

example of usage here https://github.com/grails/grails-core/blob/master/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L71

use string keys, second arguments i the type, third argument is the default value

Getting the value will be 

      config.getProperty(“grails.plugin.springsecurity.controllerAnnotations.staticRules", Map, [:])

and if there value is a List it is a rule definitions, if it is another map, then you will have to re-add the “." and traverse through the nested values

**Comment by hakanernam** [comment]
Thanks for the info. A good starting point.

**Comment by burtbeckwith** [comment]
This works in 3.0.0.M2, but you need to change a couple of things in the test app. The core fix is to update `controllerAnnotations.staticRules` to the newer format described in the docs:

    grails.plugin.springsecurity.controllerAnnotations.staticRules = [
       [pattern: '/',               access: 'permitAll'],
       [pattern: '/error',          access: 'permitAll'],
       [pattern: '/index',          access: 'permitAll'],
       [pattern: '/index.gsp',      access: 'permitAll'],
       [pattern: '/shutdown',       access: 'permitAll'],
       [pattern: '/assets/**',      access: 'permitAll'],
       [pattern: '/**/js/**',       access: 'permitAll'],
       [pattern: '/**/css/**',      access: 'permitAll'],
       [pattern: '/**/images/**',   access: 'permitAll'],
       [pattern: '/**/favicon.ico', access: 'permitAll'],

       [pattern: '/car/**', access: 'ROLE_ADMIN'],
       [pattern: '/car.*',  access: 'ROLE_ADMIN']
    ]

Additionally note that both mappings require 'car' since the controller is what's guarded, independent of url mappings.

You also need to update BootStrap to assign ROLE_ADMIN to the test user.
