### ISSUE TITLE
403 error code for namespaced controller with Grails 3.1.1 and Spring Core Security 3.0.3

### ISSUE THREAD

**Issue by bgoetzmann** [grails-plugins/grails-spring-security-core#418]
In the Grails 3.1.1 project attached that uses Spring Core Security 3.0.3 plugin, I defined:
- a namespaced controller, Test
- 2 mappings ('/actions/action1' and '/actions/action2') that resolve to the controller's actions (index and index1)

If I access to '/actions/action1' for example I get a 403 error code.

If I remove the namespace declaration in controller and in mappings, it works as expected.

[test-app.zip](https://github.com/grails-plugins/grails-spring-security-core/files/136286/test-app.zip)

**Comment by ddelponte** [comment]
Hi @bgoetzmann and thank-you for submitting this issue!

I investigate the problem, using the attached `test-app.zip` file as guidance, and was not able to reproduce the bug as you described.

One thing I did notice is that the actions in your `TestController`, `index` and `index1`, are missing the `@Secured` annotation.

Because the annotation was missing, I received a `403 - forbidden` response with or without the namespace.  That is the correct behavior.

Once the `@Secured` annotation was added to the actions, everything worked as expected.

For example:

```
class TestController {

    static namespace = 'test'

    @Secured('ROLE_ADMIN')
    def index() {
        render 'index...'
    }

    @Secured('ROLE_ADMIN')
    def index1() {
        render 'index1...'
    }
}
```

Are you able to confirm that adding the `@Secured` annotation works for you as well?

If so, I will close this issue and mark it as `Not a Bug`

More info is available at http://grails-plugins.github.io/grails-spring-security-core/3.1.x/index.html#tutorials in section 23.1.8.8

Please let me know if it works for you.

**Comment by ddelponte** [comment]
It's been > 2 years since this issue was created.  
No feedback  has been received.  
Closing.
