### ISSUE TITLE
Redirect by referer after login without using successHandler.useReferer = true

### ISSUE THREAD

**Issue by ppazos** [grails-plugins/grails-spring-security-core#432]
I'm working in a couple of 2.5.3 Grails apps using the security plugin, one uses the standard login and the other a customized auth filter.

If I go to an URL that doesn't exists inside my app, the app redirects me to the login page (expected), then when I login, I get redirected to that URL that actually doesn't exists (not expected?).

Since the doc says successHandler.useReferer = false by default (http://grails-plugins.github.io/grails-spring-security-core/v3/index.html), I would expect the plugin to redirect to grails.plugin.springsecurity.successHandler.defaultTargetUrl by default.

It seems the plugin or spring sec is using the referer. In the docs it says that successHandler.useReferer is false by default.

I went through the plugin's code and can't find where the useReferer value is used or where is set to false by the plugin (maybe due the complexity of following the references of things that are injected dynamically).

This doesn't affect the functionality of the apps, but is a little annoying because I know the URL is wrong, but the app is showing "you don't have permissions to see this page bla bla bla ..." instead of 404. I would like to differentiate a 401 Unauthorized from a 404 Not Found and control what to do on each case.

I'm wondering if this is a bug and if anyone else is experiencing something similar.

Thanks!

**Comment by ddelponte** [comment]
@ppazos what you are describing here is the expected behavior. This does not appear to be a bug.

By default, the user will always be redirected to the requested url after authentication. The referer is not being used.

`useReferer` is set to false in [`grails-app/conf/DefaultSecurityConfig.groovy`](https://github.com/grails-plugins/grails-spring-security-core/blob/master/plugin/grails-app/conf/DefaultSecurityConfig.groovy#L122)

Requesting a URL which doesn't exist will result in a 403-forbidden status which will display the `access denied` page.

You can customize this behavior by overriding `LoginController.denied()` and adding the logic you require.
