### ISSUE TITLE
org.springframework.expression.spel.SpelParseException: EL1041E: After parsing a valid expression, there is still more data in the expression: 'comma(,)'

### ISSUE THREAD

**Issue by lmiranda** [grails-plugins/grails-spring-security-core#518]
Code quoted from documentation:
`new Requestmap(url: '/admin/user/**', configAttribute: 'GROUP_ADMIN,GROUP_SUPERVISOR').save()`  When theres more than one Group in a single configAtributte, it throws the following exception:
**org.springframework.expression.spel.SpelParseException: EL1041E: After parsing a valid expression, there is still more data in the expression: 'comma(,)**

**Comment by ddelponte** [comment]
As a followup:

It's my understanding that the `configAttribute` property may contain a comma delimited list of required roles, SpEL expressions, and/or tokens.  So, I think the problem is that your `configAttribute` `String` contains groups, not roles.

So, something like `new RequestMap(url: url, configAttribute: "ROLE_USER, ROLE_ADMIN").save()` may work.

The logic is that if the attribute starts with "ROLE_" then it's considered a role-based attribute
