### ISSUE TITLE
Informational messages are logged with level "WARN"

### ISSUE THREAD

**Issue by davidkron** [grails-plugins/grails-spring-security-core#521]
During development I always start my applications with log level "WARN". So I discovered that grails-spring-security-core seems to log messages I would not consider warnings. And additionally, it also prints the messages with `println`, which results in duplicated output:
```
WARN grails.plugin.springsecurity.SpringSecurityCoreGrailsPlugin - 
Configuring Spring Security Core ...

Configuring Spring Security Core ...
WARN grails.plugin.springsecurity.SpringSecurityCoreGrailsPlugin - ... finished configuring Spring Security Core

... finished configuring Spring Security Core
```

Is there a reason for this behavior?
I think a simple log.debug or log.info and no println should be enough.

**Comment by ddelponte** [comment]
thank-you @davidkron for submitting this issue!

I do believe the `println`s are there so that developers may see the the current state of the `spring-security-core` plugin when the app starts, regardless of whether they've configured the correct log level (currently `warn`) in their config.

I think the `println` statements should be kept in place, but I do agree the other startup messages should be logged with level `info`.

I'll work on that change.

**Comment by sdelamo** [comment]
Personally, I think we should remove the `println` statements too.
