### ISSUE TITLE
'stop-app' not working and renders the login page HTML to console

### ISSUE THREAD

**Issue by aadrian** [grails-plugins/grails-spring-security-core#536]
Using the latest version of this plug-in (3.2.1 or even 3.2.0) with Grails 3.3.3, this prevents the apps
from being stopped in development mode with `stop-app`.

When calling `stop-app`, the HTML content of the login page is rendered to the console, than input/output seems frozen on Windows (7,8,10) :( .

This makes interactive development extremely annoying :( .

Thank you.

**Comment by goedef** [comment]
I assume the problem comes from grails 3.3.3. I tried to upgrade from 3.3.2 and I get unexpected behaviour in various parts (Delet for instances does not pass al variables anymore.) Stay away from 3.3.3 fro now.

Fred

Van: aadrian <notifications@github.com>
Beantwoorden - Aan: grails-plugins/grails-spring-security-core <reply@reply.github.com>
Datum: maandag 19 maart 2018 om 11:56
Aan: grails-plugins/grails-spring-security-core <grails-spring-security-core@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [grails-plugins/grails-spring-security-core] 'stop-app' not working and renders the login page HTML to console (#536)


Using the latest version of this plug-in (3.2.1 or even 3.2.0) with Grails 3.3.3, this prevents the apps
from being stopped in development mode with stop-app.

When calling stop-app, the HTML content of the login page is rendered to the console, than input/output seems frozen on Windows (7,8,10) :( .

This makes interactive development extremely annoying :( .

Thank you.

**Comment by ddelponte** [comment]
@aadrian and @goedef ,I have attempted to reproduce this issue utilizing:

- macOS 10.13.4
- Java 1.8.0_144
- grails-3.3.5

I've confirmed that `grails stop-app` works if the app was started using `grails run-app`.

`grails stop-app` will not work if the app was starting using `./gradlew bootRun` or `gradle bootRun`

Can you confirm `grails stop-app` works for you if the app was started with `grails run-app`?

**Comment by aadrian** [comment]
@goedef @ddelponte I reported the issue here, since we encountered this issue only when using **this** plug-in in projects :( .

**Comment by ddelponte** [comment]
@aadrian The issue linked to at https://github.com/grails/grails-core/issues/10791 states that this is no longer an issue with the latest grails-version (currently 3.3.6).

Would you be able to update your app to grails-3.3.6 and test the `stop-app` functionality again?

**Comment by aadrian** [comment]
> Would you be able to update your app to grails-3.3.6 and test the stop-app functionality again?

@ddelponte the issue does not seem to be reproducible with 3.3.6 anymore.

Thank you!

**Comment by ddelponte** [comment]
That's great news @aadrian and thank-you so much for following up!  ✨

**Comment by jnunderwood** [comment]
I am still experiencing this issue with this v3.2.3 of this plugin when using Grails v3.3.9. It doesn't happen consistently, unfortunately. Sometimes 'stop-app' works, sometimes it outputs the login page and hangs.
