### ISSUE TITLE
Grails 6 s2-quickstart ApplicationCommand

### ISSUE THREAD

**Issue by codeconsole** [grails-plugins/grails-spring-security-core#905]
### Feature description

The [scripts](https://github.com/grails/grails-spring-security-core/tree/5.3.x/plugin/src/main/scripts) need to be converted to ApplicationCommand similar to [what was done with the scaffolding plugin](https://github.com/grails/scaffolding/commit/db2ef730a5a0839268f12e244b76254c76870da2).

**Comment by tircnf** [comment]
I've added some comments to:
https://github.com/grails/grails-spring-security-core/commit/2d6d5b67e1e7780e771fe4ba984e671f87b6bbda

where the s2-quickstart was created as an applicationCommand.

`createDomains` is looking for gorm.version in the properties file which isn't there anymore causing it to create old versions of User with an injected `springSecurityService` instead of the interceptor.

If you manually add gorm.version to the gradle.properties file, then

The refactor of `extractVersion` turned the LinkedHashMap into a HashMap which breaks the sorting code used in `versionAfterOrEqualsToThreshold`.   The version number can come back in a random order based on the order the items are returned from the HashMap.

**Comment by puneetbehl** [comment]
I think we can completely remove this version check. I am not sure if it makes sense now.

**Comment by codeconsole** [comment]
Considering this version of the plugin is only supposed to work with Grails 6, there is no need to test for older versions.
